name: dentity
description: A powerful and flexible Entity-Component-System (ECS) framework for Dart application.
version: 1.0.0
repository: https://github.com/LeeMatthewHiggins/dentity
homepage: https://www.wearemobilefirst.com

environment:
  sdk: ^3.4.3

# Add regular dependencies here.
dependencies:
  # path: ^1.8.0

dev_dependencies:
  lints: ^3.0.0
  test: ^1.24.0
